// Add any unique troubleshooting steps here.

For troubleshooting common Partner Solution issues, refer to the https://fwd.aws/rA69w?[AWS Partner Solution General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

// == Resources
// Uncomment section and add links to any external resources that are specified by the partner.

=== FAQ

*Q.* The IPsec tag doesn’t change to IPSec:enabled when I launch an EC2 instance.

*A.* If you encounter this issue:

* Wait two minutes after the EC2 instance launches, so that it becomes reachable by AWS Systems Manager.
* Check that the EC2 instance has the right role assigned for SSM Agent. The role is provisioned by the solution named Ec2IPsec-\{stackname}.
* Check that SSM Agent is reachable through a NAT gateway, an internet gateway, or a private SSM endpoint.
* *For CentOS and RHEL, check that you’ve installed SSM Agent, as described in link:#step-4.-optional-launch-an-ec2-instance-for-testing[step 4] of the deployment steps.
* Check the output of SSM Agent command execution in the Amazon EC2 console.
* Check the IPSecSetup Lambda logs in CloudWatch for troubleshooting details.

*Q.* The IPsec connection is lost after a few hours and can only be established from one host (in one direction).

*A.* If you encounter this issue:

* Check that your security groups allow the ESP protocol and UDP 500. Security groups are stateful. They might allow only a single direction when establishing IPsec.
* Check that your network ACL allows the ESP protocol and UDP 500.

*Q.* An SNS alarm was triggered upon IPsec re-enrollment, but everything seems to work fine.

*A.* Check for the following:

* Certificates are valid for 30 days and rotated every week. If the rotation fails, you have three weeks to fix the problem.
* Check that your EC2 instances are reachable over AWS Systems Manager. If they are, trigger the Lambda function for certificate rotation again.
* See the IPSecSetup Lambda logs in CloudWatch for troubleshooting details.

*Q.* Route 53 (DNS), Amazon RDS, and other AWS managed services are not reachable.

*A.* Route 53, Amazon RDS, and other AWS managed services do not support IPsec. You need to exclude them from encryption by listing them in the config/clear list. For details, see link:#step-3.-configure-the-ipsec-network[step 3] of the deployment steps.

*Q.* The IPsec tag changed to IPSec:enabled when the EC2 instance launched, but there is no network communication to any address.

*A.* Check the IPsec network configuration. The files clear, private, private-to-clear, and clear-to-ipsec should contain your network ranges, as discussed in link:#step-3.-configure-the-ipsec-network[step 3] of the deployment steps.

*Q.* I encountered another issue that isn’t listed here.

*A.* Here are some additional general IPsec commands you can use for troubleshooting:

To stop IPsec, run this Unix command:

----
sudo ipsec stop
----

If you want to stop IPsec on all instances, you can run this command in AWS Systems Manager on all instances that have the tag IPSec:enabled. Stopping encryption means that all traffic will be sent unencrypted.

If you want to have a fail-open case, meaning that an IKE (IPsec) failure sends the unencrypted data, you should configure your network in the config/private-or-clear file, as described in link:#step-3.-configure-the-ipsec-network[step 3] of the deployment steps.

To troubleshoot IPsec issues, you can use https://libreswan.org/man/[Libreswan commands] such as the following:

----
sudo ipsec status

sudo ipsec barf

ipsec whack --oppohere <src-ip-address> --oppothere <dst-ip-address>
----

where <src-ip-address> and <dst-ip-address> are the source and destination IP addresses to test.

== Security 

The CA key is encrypted using an Advanced Encryption Standard (AES) 256 CBC 128-byte secret and stored in a bucket with server-side encryption (SSE). The secret is https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#enveloping[envelope-encrypted] with a CMK in AWS KMS. Only the certificate-issuing Lambda function can decrypt the secret (https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html[AWS KMS resource policy]). The encrypted secret for the CA key is set in an encrypted environment variable of the certificate-issuing Lambda function.

The IPsec host private key is generated by the certificate-issuing Lambda function. The private key and certificate are encrypted with AES 256 CBC (PKCS #12) and protected with a 128-byte secret generated by AWS KMS. The secret is envelope-encrypted with a user CMK. Only the EC2 instances that have an attached IPsec IAM policy can decrypt the secret and private key.

The issuing of the certificate is a full synchronous call; that is, one request and one corresponding response without any polling or similar sync/callbacks. The host private key is not stored in a database or in an S3 bucket.

The issued certificates are valid for 30 days and are stored for auditing purposes in a certificates bucket without a private key.

== Alternate subject names and multiple interfaces or secondary IPs

The certificate subject name and *AltSubjectName* attribute contains the private DNS of the EC2 instance and all private IPs assigned to the instance (interfaces, primary and secondary IPs).

The default Libreswan configuration we’ve provided covers a single interface. If you want to cover multiple interfaces—for example, to cover https://aws.amazon.com/eks/[Amazon Elastic Container Service for Kubernetes (Amazon EKS)]—you can adjust the configuration by following the instructions in the https://libreswan.org/man/ipsec.conf.5.html[Libreswan documentation].
